FROM arm64v8/python:3.9-slim

WORKDIR /app
COPY ./requirements-actions.txt /app/
RUN pip install --upgrade pip && \
    pip install -r requirements-actions.txt
COPY ./rasa/actions /app/actions

CMD ["rasa", "run", "actions", "--actions", "actions", "--port", "5055"]
