apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa
  template:
    metadata:
      labels:
        app: rasa
    spec:
      containers:
      - name: rasa
        image: eyecandy101/rasa:latest
        ports:
        - containerPort: 5005
        volumeMounts:
        - name: rasa-config-volume
          mountPath: /app/config
          readOnly: true 
      volumes:
      - name: rasa-config-volume
        configMap:
          name: rasa-config
---
apiVersion: v1
kind: Service
metadata:
  name: rasa-service
spec:
  selector:
    app: rasa
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
  type: LoadBalancer
